### PR TITLE
initial commit with updated readmen and .gitignore file

### PR DESCRIPTION
**Pull request by DreRandaci**

### CODE REVIEW

**Comment by DreRandaci** [comment]
@daviddassau @RobertShock @johnachor check this out

**Comment by johnachor** [comment]
Unsatisfactory

**Comment by RobertShock** [comment]
👍

**Comment by daviddassau** [comment]
👍

**Comment by DreRandaci** [comment]
IM FUCKING DOING IT!!!!

**Comment by johnachor** [comment]
#yolo

**Pull request merged**
